In [38]:
import numpy as np
import scipy.linalg as la
from scipy import optimize


np.set_printoptions(suppress=True)

In [45]:
def func(x, *args, **kwargs):
    distorted = args[0]
    true      = args[1]
    
    A = x[:9].reshape((3, 3))
    b = x[9:]
    
    guess    = la.inv(A) @ (distorted - b[:, np.newaxis])
    vec_diff = la.norm((true - guess)**2, axis=1)
    
    return la.norm(vec_diff)

In [36]:
true_A = np.array([[0.1,   0,   4],
                   [  0,   2, 0.5],
                   [  4, 0.5,   1]])
true_b = np.array([1, 10, -2])

true_data = np.array([[1, 0, 0],
                      [0, 1, 0],
                      [0, 0, 1]])
noise_data = (true_data @ true_A) + true_b[:, np.newaxis]

print('true_data')
print(true_data)
print()
print('noise_data')
print(noise_data)

true_data
[[1 0 0]
 [0 1 0]
 [0 0 1]]

noise_data
[[ 1.1  1.   5. ]
 [10.  12.  10.5]
 [ 2.  -1.5 -1. ]]


In [51]:
test_A = np.array([[1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1]])
test_b = np.array([0, 0, 0])

res = optimize.minimize(func,
                        np.hstack([true_A.flatten(), true_b.flatten()]),
                        (noise_data, true_data),
                        method='Nelder-Mead').x

opt_A = res[:9].reshape((3, 3))
opt_b = res[9:]

print('opt_A')
print(opt_A)
print()
print('opt_b')
print(opt_b)

opt_A
[[0.1 0.  4. ]
 [0.  2.  0.5]
 [4.  0.5 1. ]]

opt_b
[ 1. 10. -2.]
