In [1]:
import numpy as np
import scipy.linalg as la
from scipy import optimize


np.set_printoptions(suppress=True)

In [2]:
def func(x, *args, **kwargs):
    distorted = args[0]
    true      = args[1]
    
    A = x[:9].reshape((3, 3))
    b = x[9:]
    
    guess    = la.inv(A) @ (distorted - b[:, np.newaxis])
    vec_diff = la.norm((true - guess)**2, axis=1)
    
    return la.norm(vec_diff)

In [3]:
true_A = np.array([[0.1,   0,   4],
                   [  0,   2, 0.5],
                   [  4, 0.5,   1]])
true_b = np.array([1, 10, -2])

true_data = np.array([[1, 0, 0],
                      [0, 1, 0],
                      [0, 0, 1]])
noise_data = (true_A @ true_data) + true_b[:, np.newaxis]

print('true_data')
print(true_data)
print()
print('noise_data')
print(noise_data)

true_data
[[1 0 0]
 [0 1 0]
 [0 0 1]]

noise_data
[[ 1.1  1.   5. ]
 [10.  12.  10.5]
 [ 2.  -1.5 -1. ]]


In [11]:
test_b = np.zeros(3)#noise_data.mean(axis=1)
test_A = np.array([[1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1]])

res = optimize.minimize(func,
                        np.hstack([test_A.flatten(), test_b.flatten()]),
                        (noise_data, true_data),
                        method='Nelder-Mead').x

opt_A = res[:9].reshape((3, 3))
opt_b = res[9:]

print('opt_A')
print(opt_A)
print()
print('opt_b')
print(opt_b)

opt_A
[[33.04439272  8.71569683 -2.42281547]
 [ 6.82277031  2.07299707 -8.42978   ]
 [-5.69830434  5.94687931 33.58603058]]

opt_b
[ -9.39067133  11.54684477 -12.8368747 ]


In [12]:
cal_data = la.inv(opt_A) @ (noise_data - test_b[:, np.newaxis])
print('cal_data')
print(cal_data)

cal_data
[[-1.36626862 -1.53798865 -1.1358607 ]
 [ 5.01167003  5.58591747  4.59225828]
 [-1.05964327 -1.29466637 -1.03561168]]
